name: Build and test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  checks:
    uses: bertie-mc/bertie-ci/.github/workflows/neoforge-mod.yml@v2.0.1
    with:
      sides: both
      fixture: rustic-engineer
