name: Build and test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    uses: bertie-mc/bertie-ci/.github/workflows/build-mod.yml@v4.0.0

  unit-test:
    uses: bertie-mc/bertie-ci/.github/workflows/unit-test.yml@v4.0.0
